mutation CreateTablaDibujo (
	$Codigo: String,
	$Marca: String,
	$Especificaciones: String,
	$Estado: String
){
  CreateTablaDibujo (
    Codigo: $Codigo,
    Marca: $Marca,
    Especificaciones: $Especificaciones,
    Estado: $Estado
  ) {
    Id
    Codigo
    Marca
    Especificaciones
    Estado
  }
}
