mutation CreateVideobean (
	$Codigo: String,
	$Marca: String,
	$Modelo: String,
	$Especificaciones: String,
	$Accesorios: String,
	$Estado: String
){
  CreateVideobean (
    Codigo: $Codigo,
    Marca: $Marca,
    Modelo: $Modelo,
    Especificaciones: $Especificaciones,
    Accesorios: $Accesorios,
    Estado: $Estado
  ) {
    Id
    Codigo
    Marca
    Modelo
    Especificaciones
    Accesorios
    Estado
  }
}
