mutation UpdateTabladibujo (
	$Id: Int,
	$Codigo: String,
	$Marca: String,
	$Especificaciones: String,
	$Estado: String,
){
  UpdateTabladibujo (
    Id: $Id,
    Codigo: $Codigo,
    Marca: $Marca,
    Especificaciones: $Especificaciones,
    Estado: $Estado
  ) {
    Id
    Codigo
    Marca
    Especificaciones
    Estado
  }
}
