query Videobeans (
	$Id: Int,
	$Codigo: String,
	$Marca: String,
	$Modelo: String,
	$Especificaciones: String,
	$Accesorios: String,
	$Estado: String
){
  VideoBeans (
    Id: $Id,
    Codigo: $Codigo,
    Marca: $Marca,
    Modelo: $Modelo,
    Especificaciones: $Especificaciones,
    Accesorios: $Accesorios,
    Estado: $Estado
  ) {
    Id
    Codigo
    Marca
		Modelo
    Especificaciones
    Accesorios
    Estado
  }
}
